version: '3'

services:
  nestjs:
    build: ./
    container_name: flance_api
    ports:
      - '80:3000'
    environment:
      - INFURA_API_URL={INFURA_API_URL}
      - TOKEN_CONTRACT_ADDRESS={TOKEN_CONTRACT_ADDRESS}
